---
redis_version: "8.10.0"

redis_port: 6379
redis_bind: "127.0.0.1"

redis_user: "redis"
redis_group: "redis"

redis_config_dir: "/etc/redis"
redis_data_dir: "/var/lib/redis"
redis_log_dir: "/var/log/redis"

redis_config_file: "/etc/redis/redis.conf"

redis_service_name: "redis"

redis_maxmemory: "256mb"
redis_maxmemory_policy: "noeviction"

redis_appendonly: "yes"
redis_protected_mode: "yes"
